packages:
  - frontend
  - backend
  - contracts
  - packages/*

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  hono@<4.10.3: '>=4.10.3'
  hono@>=1.1.0 <4.10.2: '>=4.10.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  next@>=15.5.0-canary.0 <15.5.7: '>=15.5.7'
  next@>=15.5.1-canary.0 <15.5.8: '>=15.5.8'
  tar@=7.5.1: '>=7.5.2'
