packages:
  - frontend
  - backend
  - contracts
  - packages/*

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  hono@<4.10.3: '>=4.10.3'
  hono@<4.11.4: '>=4.11.4'
  hono@<4.11.7: '>=4.11.7'
  hono@>=1.1.0 <4.10.2: '>=4.10.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  next@>=15.5.0-canary.0 <15.5.7: '>=15.5.7'
  next@>=15.5.1-canary.0 <15.5.8: '>=15.5.8'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.0.11: '>=16.0.11'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  tar@=7.5.1: '>=7.5.2'
  undici@<6.23.0: '>=6.23.0'
